MdeModulePkg: Enabling OS boot from SD card
tianocore/edk2 pull request #2407
Opened 2022-01-12 12:05 UTC by aimanrosli23

There are few changes has been made:
   1. For SdMmmcHcInitClockFreq function, it modified on the input of the function.
      This is due, effecting on SD card detection.
   2. Few lines need to remove as dependency from ClockFreq function affecting on SD card initilization
      and card slot definition.
   3. Add 50ms delay during voltage switching from 3.3V to 1.8V.
   4  Add force 3.3V in a while loop if the card card failed to power in
      some cases.
Through all the changes, make it enable to boot OS from SD card through
UEFI payload.

Signed-off-by: Aiman Rosli <muhammad.aiman.rosli@intel.com>

2022-01-12 12:27 UTC, aimanrosli23 commented
Hi, 

Please help review this patch, 

Cc: Liming Gao gaoliming@byosoft.com.cn
Cc: Jian J Wang jian.j.wang@intel.com
Cc: Hao A Wu hao.a.wu@intel.com
Cc: Ray Ni ray.ni@intel.com
Cc: Zhichao Gao zhichao.gao@intel.com

Thank you.

2022-01-13 08:11 UTC, hwu25 requested changes
**Please** make your changes based on the latest content in driver SdMmcPciHcDxe.

2022-01-13 08:11 UTC, hwu25 commented on MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.c
> +  @param[in] PciIo          The PCI IO protocol instance.
@aimanrosli23 
For the changes in file SdMmcPciHci.c, please make sure that you do not revert the changes made by the below commits:
SHA-1: 49accdedf956f175041040e677163b7cbb746283
* MdeModulePkg/SdMmcPciHcDxe: Hook SwitchClockFreq after SD clock start

SHA-1: c67617f3c677c342efde780e229f841f4e0f6c7e
* MdeModulePkg/SdMmcPciHcDxe: Add retries for sync commands

SHA-1: 6d387610855ee27b49cb720de29ed809ea59dadc
* MdeModulePkg/SdMmcPciHcDxe: Read response on command completion

SHA-1: 63fd7f389874081ea37452b1f79ac013d52755e3
* MdeModulePkg/SdMmcPciHcDxe: Do not map memory for non DMA transfer

2022-01-13 08:11 UTC, hwu25 commented on MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.h
> +//
@aimanrosli23 
Why this change is needed?

2022-01-13 08:11 UTC, hwu25 commented on MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.h
> +/**
@aimanrosli23 
Please ensure you do not revert the changes made in commit:
SHA-1: 49accdedf956f175041040e677163b7cbb746283
* MdeModulePkg/SdMmcPciHcDxe: Hook SwitchClockFreq after SD clock start

2022-01-14 10:46 UTC, closed without merging