Mm header defination branch
tianocore/edk2 pull request #5681
Opened 2024-05-24 02:58 UTC by jiaxinwu

2024-05-31 01:54 UTC, jiaxinwu commented
Comment from Hongbin:  MdeModulePkg could not depended on UefiCpuPkg, so commbufferhob header could not put to ueficpupkg:

UefiCpuPkg: Add MM Communication Buffer header file and GUID
MM communication buffer structure including following parameters:
1.FixedCommBuffer: Buffer for data transmission between MM
communication protocol and MMI handler.
2.FixedCommBufferSize: The fixed communication buffer size.
3.CommunicationInOut: it will include return status, return
buffer size and communication buffer flag.

2024-05-31 02:18 UTC, hongbin123 commented
> Comment from Hongbin: MdeModulePkg could not depended on UefiCpuPkg, so commbufferhob header could not put to ueficpupkg:
> 
> UefiCpuPkg: Add MM Communication Buffer header file and GUID MM communication buffer structure including following parameters: 1.FixedCommBuffer: Buffer for data transmission between MM communication protocol and MMI handler. 2.FixedCommBufferSize: The fixed communication buffer size. 3.CommunicationInOut: it will include return status, return buffer size and communication buffer flag.

Another comments : some commits have two Signed-off-by, if it need to change one singed-off-by ?

2024-05-31 05:13 UTC, jiaxinwu commented
> > Comment from Hongbin: MdeModulePkg could not depended on UefiCpuPkg, so commbufferhob header could not put to ueficpupkg:
> > UefiCpuPkg: Add MM Communication Buffer header file and GUID MM communication buffer structure including following parameters: 1.FixedCommBuffer: Buffer for data transmission between MM communication protocol and MMI handler. 2.FixedCommBufferSize: The fixed communication buffer size. 3.CommunicationInOut: it will include return status, return buffer size and communication buffer flag.
> 
> Another comments : some commits have two Signed-off-by, if it need to change one singed-off-by ?

Becasue more than one contributer for such kind of patches, so no need change, we can have mutiple owner for the patch.

2024-06-28 08:51 UTC, niruiyu requested changes

2024-07-05 03:17 UTC, closed without merging