Get fixedcommbuffer from commbufferhob
tianocore/edk2 pull request #5704
Opened 2024-05-30 10:02 UTC by hongbin123

# Description

<_Include a description of the change and why this change was made._>

<_For each item, place an "x" in between `[` and `]` if true. Example: `[x]` (you can also check items in GitHub UI)_>

<_Create the PR as a Draft PR if it is only created to run CI checks._>

<_Delete lines in \<\> tags before creating the PR._>

- [ ] Breaking change?
  - **Breaking change** - Will this cause a break in build or boot behavior?
  - Examples: Add a new library class or move a module to a different repo.
- [ ] Impacts security?
  - **Security** - Does the change have a direct security impact?
  - Examples: Crypto algorithm change or buffer overflow fix.
- [ ] Includes tests?
  - **Tests** - Does the change include any explicit test code?
  - Examples: Unit tests or integration tests.

## How This Was Tested

<_Describe the test(s) that were run to verify the changes._>

## Integration Instructions

<_Describe how these changes should be integrated. Use N/A if nothing is required._>

2024-05-30 16:09 UTC, mdkinney commented
There should only be a single Signed-off-by line in commit messages.  One of the commits has the following:

Signed-off-by: Hongbin1 Zhang <hongbin1.zhang@intel.com>
Signed-off-by: Jiaxin Wu <jiaxin.wu@intel.com>

2024-05-31 02:07 UTC, hongbin123 commented
> There should only be a single Signed-off-by line in commit messages. One of the commits has the following:
> 
> Signed-off-by: Hongbin1 Zhang [hongbin1.zhang@intel.com](mailto:hongbin1.zhang@intel.com) Signed-off-by: Jiaxin Wu [jiaxin.wu@intel.com](mailto:jiaxin.wu@intel.com)

Thanks Michael, i will update it

2024-06-27 07:09 UTC, niruiyu requested changes

2024-06-28 09:46 UTC, hongbin123 commented on MdeModulePkg/Universal/SmmCommunicationBufferDxe/SmmCommunicationBufferDxe.c
Updated commit message

2024-10-21 23:42 UTC, closed without merging