For test: VarCheckHiiLibStandaloneMM
tianocore/edk2 pull request #5717
Opened 2024-06-03 08:10 UTC by xieyuanh

# Description

<_Include a description of the change and why this change was made._>

<_For each item, place an "x" in between `[` and `]` if true. Example: `[x]` (you can also check items in GitHub UI)_>

<_Create the PR as a Draft PR if it is only created to run CI checks._>

<_Delete lines in \<\> tags before creating the PR._>

- [ ] Breaking change?
  - **Breaking change** - Will this cause a break in build or boot behavior?
  - Examples: Add a new library class or move a module to a different repo.
- [ ] Impacts security?
  - **Security** - Does the change have a direct security impact?
  - Examples: Crypto algorithm change or buffer overflow fix.
- [ ] Includes tests?
  - **Tests** - Does the change include any explicit test code?
  - Examples: Unit tests or integration tests.

## How This Was Tested

<_Describe the test(s) that were run to verify the changes._>

## Integration Instructions

<_Describe how these changes should be integrated. Use N/A if nothing is required._>

2024-06-17 07:32 UTC, jiaxinwu commented on StandaloneMmPkg/StandaloneMmPkg.dsc
> +  VarCheckHiiLibMmDependency|MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibMmDependency.inf
no need add in standalonemmpkg

2024-06-17 07:36 UTC, jiaxinwu commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibMmDependency.inf
> +  StandaloneMmPkg/StandaloneMmPkg.dec
check why need StandaloneMmPkg.dec?

2024-06-17 07:54 UTC, jiaxinwu commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibMmDependency.c
> +  // Retrieve SMM Communication Region Table
//
// XXX
//

2024-06-17 07:56 UTC, jiaxinwu commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibMmDependency.c
> +  CopyMem (VarCheckHiiVariable, mVarCheckHiiBinMmSend, mVarCheckHiiBinMmSendSize); // seperate
remove the comment.

2024-06-25 02:48 UTC, jiaxinwu approved these changes

2024-06-25 02:48 UTC, jiaxinwu commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibMmDependency.inf
> +  gEfiVariableCheckHiiCommunicationGuid
add gEdkiiPiSmmCommunicationRegionTableGuid

2024-07-01 08:40 UTC, jiaxinwu commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibMmDependency.c
> +  Status = gBS->CreateEventEx (EVT_NOTIFY_SIGNAL, TPL_NOTIFY, SmmEndOfDxeNotify, NULL, &gEfiEndOfDxeEventGroupGuid, &Event);
change SmmEndOfDxeNotify to VarCheckHiiLibSmmEndOfDxeNotify

2024-07-01 09:00 UTC, jiaxinwu commented on MdeModulePkg/MdeModulePkg.dsc
> +  VarCheckHiiLib|MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMM.inf
add VarCheckHiiLibMmDependency in libclass

2024-07-01 09:03 UTC, jiaxinwu commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibNullClass.c
> +#include "VarCheckHiiGen.h"
clean up related and duplicate code/function: like HiiOpCodeToStr

2024-07-05 10:00 UTC, lzeng14 commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibMmDependency.inf
> +#  VarCheckHiiLib Dependency DXE Driver.
could we eliminate "DXE Driver" here since it is library ?

2024-07-05 15:04 UTC, niruiyu requested changes
Minor comments are provided.

2024-07-05 15:04 UTC, niruiyu commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMM.c
> +  IN EFI_HANDLE  DispatchHandle,
VarCheckHiiLibRegisterMmHandler->VarCheckHiiLibReceiveHiiBinHandler.
The corresponding handler GUID can be gVarCheckReceiveHiiBinHandlerGuid.

2024-07-05 15:04 UTC, niruiyu commented on MdeModulePkg/MdeModulePkg.dec
> +  gEfiVariableCheckHiiCommunicationGuid  = { 0xabcdef12, 0x3456, 0x7890, { 0xab, 0xcd, 0xef, 0x12, 0x34, 0x56, 0x78, 0x90 }}
Agree with @lzeng14. Do not define in DEC file.
define GUID macro VAR_CHECK_RECEIVE_HII_BIN_HANDLER_GUID in VarCheckHii.h.
Then use it in both VarCheckHiiLibMmDependency.c and VarCheckHiiLibStandaloneMm.c

2024-07-08 00:57 UTC, jiaxinwu requested changes
please update following the comments

2024-07-08 02:26 UTC, xieyuanh commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMM.c
> +
Hi Ray. The standalone and traditional versions use different binaries, represented by mVarCheckHiiBin and mVarCheckHiiBinReceived respectively. Therefore, I think VarCheckLibRegisterSetVariableCheckHandler needs to use different implementations of CheckHiiVariableCommon. The warpper can also void code duplication.

2024-07-08 02:26 UTC, xieyuanh commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMM.c
> +
> Both SMM and MM version of SetVariableCheckHandlerHiiSmm/Mm are the same. You can just keep CheckHiiVariableCommon and remove the other two wrapper functions. The VarCheckLibRegisterSetVariableCheckHandler() can directly use CheckHiiVariableCommon.

Hi Ray. The standalone and traditional versions use different binaries, represented by mVarCheckHiiBin and mVarCheckHiiBinReceived respectively. Therefore, I think VarCheckLibRegisterSetVariableCheckHandler needs to use different implementations of CheckHiiVariableCommon. The warpper can also void code duplication.

2024-07-08 02:34 UTC, xieyuanh commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibNullClass.c
> This file is for traditional SMM. Is it better to rename it as VarCheckHiiLibSmm.c?

Yes, thanks

2024-07-16 05:23 UTC, jiaxinwu commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiGen.c
> +EFI_GUID  gVarCheckReceivedHiiBinHandlerGuid = VAR_CHECK_RECEIVED_HII_BIN_HANDLER_GUID;
should move to VarCheckHii.h:

extern EFI_GUID  gVarCheckReceivedHiiBinHandlerGuid = VAR_CHECK_RECEIVED_HII_BIN_HANDLER_GUID;

2024-07-16 05:39 UTC, jiaxinwu commented
spell wrong: mMmRecievedVarCheckHiiBin

2024-07-22 02:27 UTC, xuweiintel commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMM.inf
> +  StandaloneMmMemLib
StandaloneMmMemLib seems unused?

2024-07-22 02:27 UTC, xuweiintel commented on MdeModulePkg/MdeModulePkg.dsc
> +  MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMM.inf
Rename VarCheckHiiLibStandaloneMM to VarCheckHiiLibStandaloneMm?

2024-07-22 02:27 UTC, xuweiintel commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMM.inf
> +  VarCheckHiiGen.c
VarCheckHiiGen.c is not needed for VarCheckHiiLibStandaloneMM.inf?

2024-07-22 02:27 UTC, xuweiintel commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLib.inf
> +  CONSTRUCTOR                    = VarCheckHiiLibSmmConstructor
The lib also supports DXE_RUNTIME_DRIVER type. Why changing to VarCheckHiiLib**Smm**?

2024-07-22 02:27 UTC, xuweiintel commented on MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibCommon.c
> +#include <Library/MemoryAllocationLib.h>
The following header files are not needed for this source file.

#include <Library/MemoryAllocationLib.h>
#include <Library/MmServicesTableLib.h>
#include <Protocol/MmCommunication.h>
#include <Library/VarCheckLib.h>

2025-02-23 23:39 UTC, closed without merging