UefiCpuPkg: Add CpuExceptionHandlerHookLib to ExceptionHandlerLibs
tianocore/edk2 pull request #5727
Opened 2024-06-03 20:03 UTC by apop5

# Description

Add CpuExceptionHandlerHookLib to the ExceptionHandlerLibs. 

Library allows for platforms to perform additional functionality when an exception occurs.

- [X] Breaking change?
  - **Breaking change** - Will this cause a break in build or boot behavior?
  - Examples: Add a new library class or move a module to a different repo.
- [ ] Impacts security?
  - **Security** - Does the change have a direct security impact?
  - Examples: Crypto algorithm change or buffer overflow fix.
- [ ] Includes tests?
  - **Tests** - Does the change include any explicit test code?
  - Examples: Unit tests or integration tests.

## How This Was Tested
Tested on system where exception was forced, verified functionality was same.

## Integration Instructions
Platforms will need to add to their DSC file a reference to in the LibraryClasses section. 

`CpuExceptionHookLib|UefiCpuPkg/Library/CpuExceptionHookLibNull/CpuExceptionHookLibNull.inf`

2024-06-06 01:45 UTC, apop5 commented
@mdkinney 

I don't have the ability to add reviewers, can you please help?

2024-07-09 06:54 UTC, kraxel approved these changes

2024-07-19 20:44 UTC, apop5 commented
@niruiyu @rahul1-kumar @jiaxinwu 

@tperard 
Can you please review this PR?

2024-07-31 23:52 UTC, apop5 commented
> I do not like this change. It's a backward incompatible change that requires massive platform DSC changes to accept the new CpuExceptionhandlerHookLib.
> 
> And, why not register a new platform handler?

@niruiyu 
Yes, the change is large, and it requires a lot of platform modification to come back into compliance. 

The use case it to be able to log data, in this case, to the BMC when a CPU exception occurs, and this requires access to the cpu context for where the exception was triggered.

I am open to any suggestions that would make this chance less invasive, but with I don't see how a new handler would give access to the context in the case that an exception occurs.

2024-10-07 21:15 UTC, tlendacky commented
Can't this be done such that it doesn't break the build? Can you create the NULL library, add it to all the appropriate .DSC files and then add the call to the library function from the exception handler code?

You'll also need to update all the .DSC files in the edk2-platforms repo that use the exception handler.

2024-10-24 23:15 UTC, apop5 commented
> Can't this be done such that it doesn't break the build? Can you create the NULL library, add it to all the appropriate .DSC files and then add the call to the library function from the exception handler code?
> 
> You'll also need to update all the .DSC files in the edk2-platforms repo that use the exception handler.

@tlendacky 
Yes. The commits can be further split up.

Before I do that, I would like to get back the "requested changes" that @niruiyu commented on. Once he is satisfied with the changes, I will happily split this up in a way to address your concerns.

2024-11-08 01:30 UTC, niruiyu commented
> > Can't this be done such that it doesn't break the build? Can you create the NULL library, add it to all the appropriate .DSC files and then add the call to the library function from the exception handler code?
> > You'll also need to update all the .DSC files in the edk2-platforms repo that use the exception handler.
> 
> @tlendacky Yes. The commits can be further split up.
> 
> Before I do that, I would like to get back the "requested changes" that @niruiyu commented on. Once he is satisfied with the changes, I will happily split this up in a way to address your concerns.

I don't have other better suggestions if you need to capture any exceptions during boot.
My feeling is the exception registration mechanism provided by CpuExceptionHandlerLib now becomes incapable of meeting your needs and you are not trying to enhance the mechanism but invent a new mechanism. It's like a workaround IMO.

2024-11-08 05:29 UTC, benjamindoron commented
First, is this really going to get enough use that it needs infrastructure to be built up for it? You can follow the pattern set out at https://github.com/tianocore/edk2/blob/a232e0cd2fe2bb882a5dd0cafe322a2899a44d51/UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c#L264-L287 of retrieving the IDTR, then replacing any exception handler you want (stashing first if you'd like).

Second, about registering your own exception handler: this doesn't mean to install a separate exception handler in the IDT, in case that's what you thought. See `RegisterExceptionHandler()` above, the prototype of SmiPFHandler there matches the hook you've added. Follow this example and you should get the behaviour you desire, without needing to modify this library.

2024-11-08 05:37 UTC, gdong1 approved these changes

2024-11-08 05:55 UTC, benjamindoron requested changes
Please consider whether `RegisterCpuInterruptHandler ()` meets your needs first.

2024-11-08 11:43 UTC, LeanSheng commented
I have similar concerns either @benjamindoron , and I don't we should get this merge unless those opens have been addressed. This seems not to be the proper way of doing things.

2024-11-14 06:54 UTC, niruiyu commented
@apop5,
How about defining a new lib class "DefaultCpuExceptionHandlerLib" in MdePkg? The detailed idea is as follows:

Today the logic in CpuExceptionHandlerLib when the CPU exception happens is as follows:

```c
CurrentExceptionHandler (EFI_EXCEPTION_TYPE ExceptionType, EFI_SYSTEM_CONTEXT SystemContext)
{
  Handled = False
  IF ExceptionType == VC_EXCEPTION, THEN:
    Handled = CcExitHandleVc (&ExceptionType, SystemContext);
  ELIF ExceptionType == VE_EXCEPTION, THEN:
    Handled = CcExitHandleVe (&ExceptionType, SystemContext);
  ENDIF

  IF Handled, THEN:
    RETURN
  ENDIF

  UserHandler = UserRegisteredHandler[ExceptionType];
  IF UserHandler  != null, THEN:
    UserHandler (ExceptionType, SystemContext);
  ELIF ExceptionType < 32, THEN:
    DumpCpuContext (ExceptionType, SystemContext);
    DumpPeCoffImageInfo (ExceptionType, SystemContext);
    CpuDeadLoop ();
  ENDIF
}
```

How about the new logic as follows:
```c
NewExceptionHandler (EFI_EXCEPTION_TYPE ExceptionType, EFI_SYSTEM_CONTEXT SystemContext)
{
  Handled = False
  IF ExceptionType == VC_EXCEPTION, THEN:
    Handled = CcExitHandleVc (&ExceptionType, SystemContext);
  ELIF ExceptionType == VE_EXCEPTION, THEN:
    Handled = CcExitHandleVe (&ExceptionType, SystemContext);
  ENDIF

  IF Handled, THEN:
    RETURN
  ENDIF

  Handled = DefaultCpuExceptionHandlerLib::DefaultCpuExceptionHandler(&ExceptionType, SystemContext);
  IF Handled, THEN:
    RETURN
  ENDIF

  UserHandler = UserRegisteredHandler[ExceptionType];
  IF UserHandler  != null, THEN:
    UserHandler (ExceptionType, SystemContext);
  ENDIF
}
```

You can implement the DefaultCpuExceptionHandlerLib::DefaultCpuExceptionHandler() to handle the exceptions you care about.
The default implementation in MdePkg could be:
```c
    DumpCpuContext (ExceptionType, SystemContext);
    DumpPeCoffImageInfo (ExceptionType, SystemContext);
    CpuDeadLoop ();
```

Thoughts?

2024-11-15 17:58 UTC, benjamindoron commented
If user code wants to end the interrupt without landing back at 'dump context and deadloop,' it can call its own assembly to `iret`. Also, the ordering above would change the default behaviour.

2024-11-15 19:34 UTC, mdkinney commented
> If user code wants to end the interrupt without landing back at 'dump context and deadloop,' it can call its own assembly to `iret`. Also, the ordering above would change the default behaviour.

Doing own `iret` will not work.  The exception handler flow has its own save/restore context in assembly that must be exactly matched and mat change over time.  The only way to guarantee they are matched is to return from the CpuExceptionHandlertLib.

2025-01-22 23:40 UTC, closed without merging