MdeModulePkg: Add Segment info promt for PCIe enumeration.
tianocore/edk2 pull request #5764
Opened 2024-06-11 06:05 UTC by xunfengd

Ref:https://bugzilla.tianocore.org/show_bug.cgi?id=4783

For platforms supporting multi-segments, the edk2 would only print
Bus,Dev,Func info but ignore the segments info which might cause
duplicate device scanning info. So add the segment info to PciSearchDevice
to enhance this print.

Signed-off-by: Darren Dong <darren.dong@intel.com>

2024-06-18 05:49 UTC, lgao4 commented
Looks good to me.

2024-06-18 05:50 UTC, lgao4 approved these changes

2024-07-05 05:35 UTC, niruiyu requested changes

2024-07-05 05:35 UTC, niruiyu commented on MdeModulePkg/Bus/Pci/PciBusDxe/PciEnumeratorSupport.c
> +  UINT32         Seg = 0;
Remove "=0"

2024-07-05 05:35 UTC, niruiyu commented on MdeModulePkg/Bus/Pci/PciBusDxe/PciEnumeratorSupport.c
> +    "PciBus: Discovered %s @ [%04x|%02x|%02x|%02x]  [VID = 0x%x, DID = 0x%0x]\n",
Can you check if all the below codes should be updated to include Segment information?

Edk2 • MdeModulePkg\Bus\Pci\PciBusDxe\PciCommand.c:
  238          DEBUG_WARN,
  239:         "%a: [%02x|%02x|%02x] failed to access config space at offset 0x%x\n",
  240          __func__,

Edk2 • MdeModulePkg\Bus\Pci\PciBusDxe\PciEnumerator.c:
  995          DEBUG_ERROR,
  996:         "PciBus: [%02x|%02x|%02x] was rejected due to resource confliction.\n",
  997          PciResNode->PciDev->BusNumber,

Edk2 • MdeModulePkg\Bus\Pci\PciBusDxe\PciEnumeratorSupport.c:
  230      DEBUG_INFO,
  231:     "PciBus: Discovered %s @ [%02x|%02x|%02x]  [VID = 0x%x, DID = 0x%0x]\n",
  232      IS_PCI_BRIDGE (Pci) ?     L"PPB" :

Edk2 • MdeModulePkg\Bus\Pci\PciBusDxe\PciLib.c:
  233            DEBUG_INFO,
  234:           "   Base = 0x%lx;\tLength = 0x%lx;\tAlignment = 0x%lx;\tOwner = %s [%02x|%02x|%02x:",
  235            Bar[Resource->Bar].BaseAddress,

  347        DEBUG_INFO,
  348:       "Bridge [%02x|%02x|%02x]\n",
  349        Bridge->BusNumber,

  428            DEBUG_ERROR,
  429:           "PciBus: [%02x|%02x|%02x] Adjust Pci Device Bar Size\n",
  430            PciIoDevice->BusNumber,

2024-09-16 23:39 UTC, closed without merging