MdePkg:BaseArmTrngLibNull: Assert causing FVP stalling
tianocore/edk2 pull request #6091
Opened 2024-08-22 21:08 UTC by PrachotanReddy

FVP Base Revc doesn't support Trng.
ASSERT (FALSE) is causing the boot to stall.
Replacing ASSERT with ERROR log.

- [ ] Breaking change?
  - **Breaking change** - Does this PR cause a break in build or boot behavior?
  - Examples: Does it add a new library class or move a module to a different repo.
- [ ] Impacts security?
  - **Security** - Does this PR have a direct security impact?
  - Examples: Crypto algorithm change or buffer overflow fix.
- [ ] Includes tests?
  - **Tests** - Does this PR include any explicit test code?
  - Examples: Unit tests or integration tests.

## How This Was Tested

Booted a FVP Base RevC, boot process checked out. Standard CI.

## Integration Instructions

N/A

2024-08-26 04:30 UTC, lgao4 commented
Ard: have you any comments for this change?

2024-08-27 09:36 UTC, ardbiesheuvel commented
BaseArmTrngLibNull is provided for build coverage, and should not be called in practice. So while I understand that there is an actual issue here, the fix is almost certainly wrong.

@pierregondois any thoughts? I suppose the FVP build should be updated and switch to another ArmTrngLib implementation, or just drop RngDxe and allow 'unsafe' use of the network drivers.

2024-08-27 09:36 UTC, ardbiesheuvel requested changes
This needs to be fixed in edk2-platforms not in MdePkg.

2024-08-27 10:27 UTC, pierregondois commented
I'm not sure I understand why this solution is that wrong.

Even though using `ArmPkg/Library/ArmTrngLib/ArmTrngLib.inf` for the FVP solves the issue, wouldn't the BaseArmTrngLibNull be more lightweight if we know there is no Trng backend ?

2024-08-27 16:49 UTC, ardbiesheuvel commented
> I'm not sure I understand why this solution is that wrong.
> 
> Even though using `ArmPkg/Library/ArmTrngLib/ArmTrngLib.inf` for the FVP solves the issue, wouldn't the BaseArmTrngLibNull be more lightweight if we know there is no Trng backend ?

If there is no Trng backend and no RNDR, as in this case, the platform should avoid RngDxe entirely, and define `ENABLE_UNSAFE_RNGLIB` if it intends to incorporate the network drivers. I'll work on a patch on the edk2-platforms side to address this.

2024-08-27 17:17 UTC, ardbiesheuvel commented
> > I'm not sure I understand why this solution is that wrong.
> > Even though using `ArmPkg/Library/ArmTrngLib/ArmTrngLib.inf` for the FVP solves the issue, wouldn't the BaseArmTrngLibNull be more lightweight if we know there is no Trng backend ?
> 
> If there is no Trng backend and no RNDR, as in this case, the platform should avoid RngDxe entirely, and define `ENABLE_UNSAFE_RNGLIB` if it intends to incorporate the network drivers. I'll work on a patch on the edk2-platforms side to address this.

Correction: just setting ENABLE_UNSAFE_RNGLIB should be sufficient, as it will build RngDxe with the timer based RngLib.

cc @LeviYeoReum

2024-08-27 17:29 UTC, LeviYeoReum commented
Hi @ardbiesheuvel.

This problem happens in case of
    - no TRNG
    - backend is RDNR

In `RngDxe` driver while it checks available algo via `GetAvailableAlgorithms()` in its entrypoint,
It calls `GetTrngVersion()` which makes ASSERT failure in DEBUG build in case of using BaseArmTrngLibNull.
Thou it uses timer based RngLib, It still failed.

So, I think it seems corret solution.

2024-08-27 17:33 UTC, ardbiesheuvel commented
> Hi @ardbiesheuvel.
> 
> This problem happens in case of - no TRNG - backend is RDNR
> 
> In `RngDxe` driver, while it checks available algo via `GetAvailableAlgorithms()` in its entrypoint, It calls `GetTrngVersion()` which makes ASSERT failure in DEBUG build in case of using BaseArmTrngLibNull regardless of whether it uses RNDR backend or not. Thou it uses timer based RngLib, It still failed.
> 
> So, I think it seems corret solution.

Fair enough, even though I dislike the confusion this creates for *LibNull style libraries, which generally only exist to satisfy link-time dependencies in package DSCs that do not define any actual platforms (MdePkg, MdeModulePkg).

But in this case, dropping the ASSERT() seems reasonable.

2024-08-27 17:33 UTC, ardbiesheuvel approved these changes

2024-08-28 08:04 UTC, pierregondois commented
@PrachotanReddy would it be possible to remove the commit `Merge branch 'master' into SMSC_ARM_FVP_Assert` from the PR ?

2024-08-28 14:12 UTC, PrachotanReddy commented
> @PrachotanReddy would it be possible to remove the commit `Merge branch 'master' into SMSC_ARM_FVP_Assert` from the PR ?

@pierregondois I don't see an option to remove the commit. Maybe the only option is to do a new pr?

2024-08-28 14:19 UTC, pierregondois commented
> > @PrachotanReddy would it be possible to remove the commit `Merge branch 'master' into SMSC_ARM_FVP_Assert` from the PR ?
> 
> @pierregondois I don't see an option to remove the commit. Maybe the only option is to do a new pr?

I think that you need to rebase your branch on top of master instead of merging it with master.
The following commands should allow to get the desired result:
```
git reset HEAD~ --hard
git rb origin/master
git push [...]
```

2024-08-28 14:21 UTC, PrachotanReddy commented
> > > @PrachotanReddy would it be possible to remove the commit `Merge branch 'master' into SMSC_ARM_FVP_Assert` from the PR ?
> > 
> > 
> > @pierregondois I don't see an option to remove the commit. Maybe the only option is to do a new pr?
> 
> I think that you need to rebase your branch on top of master instead of merging it with master. The following commands should allow to get the desired result:
> 
> ```
> git reset HEAD~ --hard
> git rb origin/master
> git push [...]
> ```

Done

2024-08-29 04:00 UTC, merged