Fdt rcp 0
tianocore/edk2 pull request #6094
Opened 2024-08-23 06:43 UTC by LinusvPelt

# Description

<_Include a description of the change and why this change was made._>

<_For each item, place an "x" in between `[` and `]` if true. Example: `[x]` (you can also check items in GitHub UI)_>

<_Create the PR as a Draft PR if it is only created to run CI checks._>

<_Delete lines in \<\> tags before creating the PR._>

- [ ] Breaking change?
  - **Breaking change** - Does this PR cause a break in build or boot behavior?
  - Examples: Does it add a new library class or move a module to a different repo.
- [ ] Impacts security?
  - **Security** - Does this PR have a direct security impact?
  - Examples: Crypto algorithm change or buffer overflow fix.
- [ ] Includes tests?
  - **Tests** - Does this PR include any explicit test code?
  - Examples: Unit tests or integration tests.

## How This Was Tested

<_Describe the test(s) that were run to verify the changes._>

## Integration Instructions

<_Describe how these changes should be integrated. Use N/A if nothing is required._>

2024-08-26 04:31 UTC, lgao4 commented
The change in MdePkg is good to me.

2024-08-26 15:59 UTC, ChaselChiu commented on UefiPayloadPkg/UefiPayloadPkg.dec
> +gUefiPayloadPkgTokenSpaceGuid.PcdHandOffFdtEnable|TRUE|BOOLEAN|0x00000026
Let's start with PcdHandOffFdtEnable = FALSE as default to not break existing platforms. Once those platforms are ready to use FDT they will toggle this PCD to TRUE. Later we may switch back to TRUE as default.

2024-08-26 16:36 UTC, ChaselChiu requested changes

2024-08-26 16:36 UTC, ChaselChiu commented on UefiPayloadPkg/UefiPayloadPkg.dec
> +gUefiPayloadPkgTokenSpaceGuid.PcdHandOffFdtEnable|TRUE|BOOLEAN|0x00000026
Let's start with PcdHandOffFdtEnable = FALSE as default to not break existing platforms. Once those platforms are ready to use FDT they will toggle this PCD to TRUE. Later we may switch back to TRUE as default.

2024-08-26 17:29 UTC, ChaselChiu requested changes

2024-08-26 17:29 UTC, ChaselChiu commented on UefiPayloadPkg/Include/Guid/UniversalPayloadBase.h
> +#define P_NON_PREFETCHABLE        BIT30
BIT30 set means "prefetchable", please correct the MACRO naming.

2024-08-27 05:06 UTC, ChaselChiu commented on UefiPayloadPkg/UefiPayloadPkg.dec
> +gUefiPayloadPkgTokenSpaceGuid.PcdHandOffFdtEnable|TRUE|BOOLEAN|0x00000026
resolved

2024-08-27 05:06 UTC, ChaselChiu commented on UefiPayloadPkg/Include/Guid/UniversalPayloadBase.h
> +#define P_NON_PREFETCHABLE        BIT30
resolved

2024-08-27 05:08 UTC, ChaselChiu approved these changes

2024-08-28 15:17 UTC, ChaselChiu commented
Close this PR as we do not need 2 phases merging anymore. A single PR which incorporated all the changes has been merged: https://github.com/tianocore/edk2/pull/6095

2024-08-28 15:17 UTC, closed without merging