ArmPkg: ArmMmuLib: Pre-Allocate Page Table Memory
tianocore/edk2 pull request #6286
Opened 2024-10-03 21:40 UTC by os-d

# Description

Allocating memory when memory protection is active can cause the below infinite loop:

1. gCpu->SetMemoryAttributes(EFI_MEMORY_RO)
2. ArmSetMemoryAttributes ()
3. SetMemoryRegionAttribute()
4. UpdateRegionMapping()
5. UpdateRegionMappingRecursive()
6. AllocatePages() -> Need memory for a translation table entry
7. CoreAllocatePages()
8. ApplyMemoryProtectionPolicy() -> Policy says new page should be XN
9. gCpu->SetMemoryAttributes()
10. Back to 3

To fix this previously, CpuDxe would update conventional memory to be XN prior to installing the CpuArch protocol. However, when we transition to setting EFI_MEMORY_RP on free memory, this will no longer work. This a prerequisite to bring in the EFI_MEMORY_RP on free memory feature that has been discussed on the mailing list.

This PR updates ArmMmuLib to reserve page table memory for allocation during table spits to prevent the infinite loop. This follows the same pattern that the x86 CpuDxe does to preallocate page table memory: https://github.com/tianocore/edk2/blob/f962adc8a089949ecc730ba17f08234b52e3952d/UefiCpuPkg/CpuDxe/CpuPageTable.c#L1117.

It also updates the consumers of ArmMmuLib to consume the PEI version of the lib in the same commit so as to not break them.

Continuous-integration-options: PatchCheck.ignore-multi-package

- [x] Breaking change?
  - **Breaking change** - Does this PR cause a break in build or boot behavior?
  - Examples: Does it add a new library class or move a module to a different repo.
- [ ] Impacts security?
  - **Security** - Does this PR have a direct security impact?
  - Examples: Crypto algorithm change or buffer overflow fix.
- [ ] Includes tests?
  - **Tests** - Does this PR include any explicit test code?
  - Examples: Unit tests or integration tests.

## How This Was Tested

Tested on ArmVirtQemu by creating the scenario where the infinite loop (without the XN remap routine in place) and booting successfully. This was also tested using the EFI_MEMORY_RP on free memory feature that is pending upstreaming. This has been shipping in platforms.

## Integration Instructions

Platforms which are using ArmMmuBaseLib for PEIM, PEI_CORE, and SEC
modules will need to switch those module types to use ArmMmuPeiLib.

```inf
[LibraryClasses.common.SEC, LibraryClasses.common.PEIM, LibraryClasses.common.PEI_CORE]
  ArmMmuLib|ArmPkg/Library/ArmMmuLib/ArmMmuPeiLib.inf
```

Platforms will also need to remove `gArmTokenSpaceGuid.PcdRemapUnusedMemoryNx` as it has been removed.

2024-10-09 11:54 UTC, LeviYeoReum commented
I think this patch overall good to me about the table entry pool.
But I have a question for 

> When we transition to setting EFI_MEMORY_RP on free memory, this will no longer work.

I don’t catch this sentence.
Because, the I don't know why `EFI_MEMORY_RP` affects for 
step `8. ApplyMemoryProtectionPolicy() -> Policy says new page should be XN gCpu->SetMemoryAttributes()`
The allocation of table-entry former is always type change from `EfiConventional` to `EfiBootServiceData`.
So if `PcdDxeNxMemoryProtectionPolicy` of `EfiConventional` and `EfiBootServiceData` are the same, it doesn't happen.

Also,
> when we transition to setting EFI_MEMORY_RP on free memory

If setting `EFI_MEMORY_RP` on free memory (`X address`) 
and supposes it requires to allocate table entry (In assumption that former `X address` are block-entry and `EFI_MEMORY_RO`)
While trying to allocate table entry, pool doesn't have enough space so try to expand table-entry pool
But, it returns the `X address`. Then what happen?
It seems altough it was free memory, but it would be changed with "Allocated" used by table-entry pool with "EFI_MEMORY_RP".

Because I couldn't find out discussion on maling list, above quetions seems silly.
but, Would you correct me if i miss something?

Thanks.

2024-10-09 15:45 UTC, os-d commented
> I think this patch overall good to me about the table entry pool. But I have a question for
> 
> > When we transition to setting EFI_MEMORY_RP on free memory, this will no longer work.
> 
> I don’t catch this sentence. Because, the I don't know why `EFI_MEMORY_RP` affects for step `8. ApplyMemoryProtectionPolicy() -> Policy says new page should be XN gCpu->SetMemoryAttributes()` The allocation of table-entry former is always type change from `EfiConventional` to `EfiBootServiceData`. So if `PcdDxeNxMemoryProtectionPolicy` of `EfiConventional` and `EfiBootServiceData` are the same, it doesn't happen.
> 
> Also,
> 
> > when we transition to setting EFI_MEMORY_RP on free memory
> 
> If setting `EFI_MEMORY_RP` on free memory (`X address`) and supposes it requires to allocate table entry (In assumption that former `X address` are block-entry and `EFI_MEMORY_RO`) While trying to allocate table entry, pool doesn't have enough space so try to expand table-entry pool But, it returns the `X address`. Then what happen? It seems altough it was free memory, but it would be changed with "Allocated" used by table-entry pool with "EFI_MEMORY_RP".
> 
> Because I couldn't find out discussion on maling list, above quetions seems silly. but, Would you correct me if i miss something?
> 
> Thanks.

@LeviYeoReum thanks for reviewing this PR! I apologize, I should have been clearer on the `EFI_MEMORY_RP` on free memory comments. This was discussed on the mailing list with Ray some time back and I don't quite recall where, but we have a change we are planning on upstreaming which removes FreedMemoryGuard and by default puts all memory as `EFI_MEMORY_RP`, i.e. performing that same functionality but always and in an easier to maintain way (last time I tried FreedMemoryGuard was broken on both OVMF and ArmVirtPkg). So, this PR is a prerequisite to that work being upstreamed. Here is the bulk of the change we will be upstreaming: https://github.com/microsoft/mu_basecore/pull/912/commits/e20bd7141995e345ed3e6186d85eda052f640a4a. There are other pieces that need to go in first and there will be discussion on how it looks in the end, of course.

In the `EFI_MEMORY_RP` on free memory case, Page.c sets the attributes to `EFI_MEMORY_RP` when memory is freed and then to whatever appropriate type when the memory is allocated (in your example above it would set it to `EFI_MEMORY_XP` for `EfiBootServicesData`. In order for these attribute changes to work though, we need preallocated memory for the page table pool, like x86 does.

Please let me know if you have further questions.

2024-10-09 19:21 UTC, os-d commented
> Hi @os-d. Thanks for detail explaination.
> 
> > In the EFI_MEMORY_RP on free memory case, Page.c sets the attributes to EFI_MEMORY_RP when memory is freed and then to whatever appropriate type when the memory is allocated (in your example above it would set it to EFI_MEMORY_XP for EfiBootServicesData. In order for these attribute changes to work though, we need preallocated memory for the page table pool, like x86 does.
> 
> Yes. but in `ApplyMemoryProtectionPolicy()`, If `EfiBootServiceData` and `EfiConventional` are set with "1" both by `PcdDxeNxMemoryProtectionPolicy`,
> 
> ```
>   1098   if (OldType != EfiMaxMemoryType) {
>   1099     OldAttributes = GetPermissionAttributeForMemoryType (OldType);
>   1100     if (OldAttributes == NewAttributes) {
>   1101       // policy is the same between OldType and NewType
>   1102       return EFI_SUCCESS;
>   1103     }
>   1104   }
> ```
> 
> It seems to return EFI_SUCCESS without calling gCpu->SetAttributes() by line 1100. GuardPage is type of change from/to `EfiConventaional/EfiBootServiceData` and vise versa. So if `PcdDxeNxMemoryProtectionPolicy`'s `EfiConventaional` and `EfiBootServiceData` are set 1 together, `OldAttrivutes == NewAttributes == EFI_MEMORY_XP`, It wouldn't call recursively in steps `8 & 9`.
> 
> Am I missing?
> 
> Thanks

@LeviYeoReum ,

In the `EFI_MEMORY_RP` on free memory commit, we do the below:

![image](https://github.com/user-attachments/assets/24d86c7f-4271-45df-8a49-abb0d6582282)

So `GetPermissionAttributeForMemoryType` will return `EFI_MEMORY_RP|EFI_MEMORY_XP` for `EfiConventionalMemory` and `EFI_MEMORY_XP` for  `EfiBootServicesData`, so in the code snippet you sent, `OldAttributes != NewAttributes` and we'll call `gCpu->SetMemoryAttributes`, which is what then can lead into the recursion.

2024-10-09 20:54 UTC, LeviYeoReum commented
I see. I've missed that code :) only see the Page.c.
Thanks to let me know! I understand completely

2024-10-09 20:54 UTC, LeviYeoReum approved these changes

2024-10-09 20:55 UTC, os-d commented
> I see. I've missed that code :) only see the Page.c. Thanks to let me know! I understand completely

No worries, thanks for the review!

@kraxel @leiflindholm @samimujawar can you please review?

2024-10-15 21:19 UTC, os-d commented on ArmPkg/Drivers/CpuDxe/CpuDxe.c
> +                  &gArmPageTableMemoryAllocationProtocolGuid,
> Is there a reason for installing the ArmPageTableMemoryAllocationProtocol protocol again here? It is already installed in InitializePageTableMemory(), right?

Correct, thanks. I will remove the initialization here.

> Not relevant to this patch, but I think we should return the status code if the protocol installation fails.

We should probably assert or panic (panic lib support is being added).

2024-10-15 21:21 UTC, os-d commented on ArmPkg/Drivers/CpuDxe/CpuDxe.c
> +  ASSERT_EFI_ERROR (Status);
Yes, I will add that. This would be fatal.

2024-10-15 21:44 UTC, os-d commented on ArmPkg/Drivers/CpuDxe/PageTableMemoryAllocation.c
> +#define MIN_PAGES_AVAILABLE        5
Here is the original comment from the author. I will add a comment here

![image](https://github.com/user-attachments/assets/e4940325-129a-4652-93a1-348c8adcdf6f)

2024-10-15 21:48 UTC, os-d commented on ArmPkg/Library/ArmMmuLib/AArch64/ArmMmuLibPageTableAlloc.c
> +  return AllocatePages (Pages);
I agree. At this point we should have the protocol, if not a serious error occurred.

2024-10-15 21:55 UTC, os-d commented on ArmPkg/Library/ArmMmuLib/ArmMmuPeiLib.inf
> +  CONSTRUCTOR                    = ArmMmuBaseLibConstructor
Let me retest with using ArmMmuPeiLibConstructor to see what the issue was there

2024-10-18 21:10 UTC, os-d commented on ArmPkg/Library/ArmMmuLib/ArmMmuPeiLib.inf
> +  CONSTRUCTOR                    = ArmMmuBaseLibConstructor
There was not an issue here, that I saw in booting ArmVirtQemu, so I went back to PEIM and the Pei constructor.

2024-10-18 21:14 UTC, os-d commented
@samimujawar I addressed your comments, can you please re-review?

2024-10-24 20:41 UTC, os-d commented
@samimujawar friendly ping to re-review

2024-10-25 07:19 UTC, samimujawar commented
Apologies for the delay. I will review this shortly.

2024-10-28 15:49 UTC, samimujawar reviewed
Hi Oliver,
Apologies for the delay in getting back, and thank you for the updated patch series.

I have some minor comments marked inline. 
Other than that do you plan to send a patch series to update the platforms in the edk2-platforms repo?

Regards,

Sami Mujawar

2024-10-28 15:49 UTC, samimujawar commented on ArmVirtPkg/ArmVirtKvmTool.dsc
> +[LibraryClasses.common.SEC]
Would it be possible to add these changes to ArmVirtPkg/ArmVirt.dsc.inc ?
That way we can have all these settings in a common place.

2024-10-28 21:00 UTC, os-d commented on ArmPkg/Drivers/CpuDxe/PageTableMemoryAllocation.c
> +    FreePages (Pages, EFI_SIZE_TO_PAGES (Pages->FreePages) + 1);
Agreed, I will fix this.

2024-10-28 21:11 UTC, os-d commented
> Hi Oliver, Apologies for the delay in getting back, and thank you for the updated patch series.
> 
> I have some minor comments marked inline. Other than that do you plan to send a patch series to update the platforms in the edk2-platforms repo?

Thanks for reviewing! I have pushed an update addressing your comments, can you please re-review? I will put up a PR in edk2-platforms to resolve issues there and wait to check it in until this goes in.

2024-10-28 23:09 UTC, os-d commented
Here is the edk2-platforms PR: https://github.com/tianocore/edk2-platforms/pull/235.

2024-11-05 15:50 UTC, os-d commented on ArmPkg/Library/ArmMmuLib/ArmMmuBaseLib.inf
> +  UefiBootServicesTableLib
Agreed, added

2024-11-11 10:32 UTC, samimujawar approved these changes

2024-11-11 12:26 UTC, ardbiesheuvel requested changes
This is far too intrusive.

The page table walker does not actually require readable pages, only the CPU needs these pages to be read-/writable while it is manipulating the contents, but this could potentially happen via a different mapping altogether.

Also, I don't think we have fully explored other options, including mapping some or all of the VA space eagerly.

2024-11-11 17:06 UTC, os-d commented
Hi @ardbiesheuvel ,

> This is far too intrusive.
> 

This is the same approach x86 CpuDxe takes: https://github.com/tianocore/edk2/blob/f962adc8a089949ecc730ba17f08234b52e3952d/UefiCpuPkg/CpuDxe/CpuPageTable.c#L1117. Having a pre-allocated pool feels less intrusive than eagerly mapping all DRAM ranges. However, I don't disagree that it would be cleaner to not do any memory allocations in the page table code.

> The page table walker does not actually require readable pages, only the CPU needs these pages to be read-/writable while it is manipulating the contents, but this could potentially happen via a different mapping altogether.
> 

I'm not quite following, which part of this PR are you referencing as changing the semantics here? And what change would you like to see?

> Also, I don't think we have fully explored other options, including mapping some or all of the VA space eagerly.
This is where we left things when Taylor was trying to upstream this:
- Not allocating memory in the page table manipulation code is a good thing
- Our main goal is to bring memory protection improvements to edk2. RP on free memory being one we have in Mu, which we are using this solution (matching x86) to achieve.
- Without this PR, we are blocked on bringing RP on free memory to edk2.
- We don't have the bandwidth to code up and test the eagerly allocating code
- We are concerned about the performance on server systems, but acknowledge that this could be unfounded

Do you have the bandwidth to put up a proof of concept of the eager mapping? We can test on our side and share the performance results if so.

If you do not have the bandwidth, then can we work out an acceptable version of this PR to avoid blocking upstreaming greater memory protections for edk2 and have the eager mapping be revisted (tracked in a GH issue or bugzilla) when there is bandwidth?

2024-11-11 17:35 UTC, ardbiesheuvel commented
> Hi @ardbiesheuvel ,
> 
> > This is far too intrusive.
> 
> This is the same approach x86 CpuDxe takes:
> 
> https://github.com/tianocore/edk2/blob/f962adc8a089949ecc730ba17f08234b52e3952d/UefiCpuPkg/CpuDxe/CpuPageTable.c#L1117
> 

I am aware of that. But that doesn't mean it is a good idea.

> . Having a pre-allocated pool feels less intrusive than eagerly mapping all DRAM ranges. However, I don't disagree that it would be cleaner to not do any memory allocations in the page table code.

Indeed. We'll always need to perform some allocations, but splitting block entries is tricky for multiple reasons, and there is some rather hairy code that fiddles with the MMU in order not to violate architectural rules regarding Break-Before-Make etc.

In the early code, I don't think mapping eagerly is feasible, as memory might be restricted. But later on, it should be possible, given that the one thing we have in abundance in the boot stage is RAM.

> > The page table walker does not actually require readable pages, only the CPU needs these pages to be read-/writable while it is manipulating the contents, but this could potentially happen via a different mapping altogether.
> 
> I'm not quite following, which part of this PR are you referencing as changing the semantics here? And what change would you like to see?
> 

Yeah, I should clarify that - see my long term plan below.

> > Also, I don't think we have fully explored other options, including mapping some or all of the VA space eagerly.
> > This is where we left things when Taylor was trying to upstream this:
> 
> * Not allocating memory in the page table manipulation code is a good thing
> * Our main goal is to bring memory protection improvements to edk2. RP on free memory being one we have in Mu, which we are using this solution (matching x86) to achieve.
> * Without this PR, we are blocked on bringing RP on free memory to edk2.
> * We don't have the bandwidth to code up and test the eagerly allocating code
> * We are concerned about the performance on server systems, but acknowledge that this could be unfounded
> 

Boot performance on server systems is not going to be impacted by this. And especially on servers, fiddling with the MMU and TLBs etc is likely to have a performance impact as well.

> Do you have the bandwidth to put up a proof of concept of the eager mapping? We can test on our side and share the performance results if so.
> 

Sure.

> If you do not have the bandwidth, then can we work out an acceptable version of this PR to avoid blocking upstreaming greater memory protections for edk2 and have the eager mapping be revisted (tracked in a GH issue or bugzilla) when there is bandwidth?

I have a short-term and a long-term plan:

The short-term plan is to extend the existing API so that the call that remaps all unused memory RP does so eagerly, so that no additional page allocations are needed to remap these pages when they are allocated

In the long term, what I would like to do is not map the page tables at all. Instead, we could have two sets of page tables, where the second set covers all of DRAM mapped lazily without restricted permissions, and this set is only used by the MMU library code while it is manipulating the mappings (with interrupts disabled). That way, all the dodgy code that fiddles with the MMU can go too, as the code no longer ever operates on live mappings. But it also means that page tables are never accessed via the primary set of page tables, and so all page tables can be unmapped (or mapped RP), and there is no reason to remap them writable, and that provides some robustness as well.

That would also permit us to switch back to lazy mapping, but I honestly don't think it makes a difference.

2024-11-11 17:45 UTC, os-d commented
> > Do you have the bandwidth to put up a proof of concept of the eager mapping? We can test on our side and share the performance results if so.
> 
> Sure.
> 

Thanks, I'll give it a test when it is ready.

> I have a short-term and a long-term plan:
> 
> The short-term plan is to extend the existing API so that the call that remaps all unused memory RP does so eagerly, so that no additional page allocations are needed to remap these pages when they are allocated
> 
> In the long term, what I would like to do is not map the page tables at all. Instead, we could have two sets of page tables, where the second set covers all of DRAM mapped lazily without restricted permissions, and this set is only used by the MMU library code while it is manipulating the mappings (with interrupts disabled). That way, all the dodgy code that fiddles with the MMU can go too, as the code no longer ever operates on live mappings. But it also means that page tables are never accessed via the primary set of page tables, and so all page tables can be unmapped (or mapped RP), and there is no reason to remap them writable, and that provides some robustness as well.
> 
> That would also permit us to switch back to lazy mapping, but I honestly don't think it makes a difference.

This plan makes sense to me, thanks for driving this.

2025-05-22 23:39 UTC, closed without merging