MdePkg/IndustryStandard: add definitions for CXL CEDT
tianocore/edk2 pull request #6434
Opened 2024-11-13 07:54 UTC by Ax-WangYuQuan

This adds #defines and struct typedefs for the various structure types in the CXL Early Discovery Table (CEDT).

2024-11-25 08:44 UTC, abdattar requested changes

2024-11-25 08:44 UTC, abdattar commented on MdePkg/Include/IndustryStandard/Cxl20.h
> +  UINT32                           UID;
change the UID to Uid as per EDKII coding guidelines.

2024-11-25 08:44 UTC, abdattar commented on MdePkg/Include/IndustryStandard/Cxl20.h
> +  UINT32                           CXLVersion;
change to CxlVersion

2024-11-25 08:44 UTC, abdattar commented on MdePkg/Include/IndustryStandard/Cxl30.h
> +  UINT64                               BaseHPA;
change to BaseHpa

2024-11-25 08:44 UTC, abdattar commented on MdePkg/Include/IndustryStandard/Cxl30.h
> +  UINT16                               BDF;
Bdf

2024-11-27 03:15 UTC, Ax-WangYuQuan commented
Any suggestions to resolve ”ERROR - --->Test Failed: Uncrustify Coding Standard Test NO-TARGET returned "3"
“ ？

2024-12-06 01:33 UTC, lgao4 commented
@makubacki , can you give some suggestion for this failure?

2024-12-17 05:31 UTC, lgao4 commented on MdePkg/Include/IndustryStandard/Cxl31.h
> +#define CEDT_TYPE_CSDS     0x4
Here, only need two spaces

2024-12-17 05:31 UTC, lgao4 commented on MdePkg/Include/IndustryStandard/Cxl31.h
> +  CEDT_STRUCTURE                       Header;
here only needs 4 spaces

2025-02-02 05:21 UTC, lgao4 approved these changes

2025-02-02 23:07 UTC, mdkinney approved these changes

2025-02-03 00:34 UTC, merged