OvmfPkg/CryptoPkg: Enhance C runtime functions
tianocore/edk2 pull request #6467
Opened 2024-11-25 10:31 UTC by leenasoman

As part of the effort to get Boringssl to work with EDK2, there are many C runtime apis that get referenced and are currently not implemented in EDK2. This change adds those apis to edk2.

Cc: Ard Biesheuvel <ardb+tianocore@kernel.org>
    Cc: Jordan Justen <jordan.l.justen@intel.com>
    Cc: Laszlo Ersek <lersek@redhat.com>
    Cc: Anthony Perard <anthony.perard@citrix.com>
    Cc: Julien Grall <julien@xen.org>

# Description
In particular, this change adds the following :
1. Stubs for file functions. These have been implemented to return -1 rather than 0 since there is no file system support and to fail any calls that are call into them.

3. Implementations of the following api which are referenced and used by Boringssl code :
  - strdup : string duplication function
  -  bsearch : binary search
  -  getentropy : return entropy of requested length
  -  __ashlti3 : Left shift for 128 bit integers

- [ ] Breaking change?
  - **Breaking change** - Does this PR cause a break in build or boot behavior?
  - Examples: Does it add a new library class or move a module to a different repo.
- [ ] Impacts security?
  - **Security** - Does this PR have a direct security impact?
  - Examples: Crypto algorithm change or buffer overflow fix.
- [ ] Includes tests?
  - **Tests** - Does this PR include any explicit test code?
  - Examples: Unit tests or integration tests.

## How This Was Tested
Calls to the apis are successful when tested locally.
## Integration Instructions
N/A

2024-11-27 15:48 UTC, ardbiesheuvel commented
Can you clean up the patch titles and explanations please? I see two patches with identical names.

2024-11-28 15:28 UTC, ardbiesheuvel commented
please avoid merge commits - instead, rebase your changes and force-push them to the existing branch.

Also, I expect to see a logical sequence of patches here (if more than one is needed)

2024-11-30 21:43 UTC, deeglaze commented on CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c
> +  }
from getentropy(3):

> EFAULT Part or all of the buffer specified by buffer and length
>               is not in valid addressable memory.

length == 0 is not a fault condition

2024-11-30 22:28 UTC, deeglaze commented on CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c
> +  }
```suggestion
  if (!length) {
    return 0;
  }
  if (!ArchIsRngSupported ()) {
    errno = ENOSYS;
    return -1;
  }
  if (entropyBuffer == NULL) {
    errno = EFAULT;
    return -1;
  }
  if (length > GETENTROPY_MAX) {
    errno = EIO;
    return -1;
  }
  copyLength = (length % sizeof(UINT64));
  if (copyLength) {
    ArchGetRandomNumber64(&randNum);
    CopyMem(entropyBuffer, &randNum, copyLength);
  }
  for (i = copyLength; i < length; i += sizeof (UINT64)) {
    ArchGetRandomNumber64 (entropyBuffer + i);
  }
  return 0;
}
```

There's no reason to put the conditionals in a loop other than the loop condition.

2024-11-30 23:07 UTC, deeglaze requested changes

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/Include/CrtLibSupport.h
> +  int         ( *cmp )(const void *, const void *)
```suggestion
  size_t nmemb,
  size_t size,
  int       ( *compar )(const void *, const void *)
```

Use the same names as bsearch(3).

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/Include/CrtLibSupport.h
> +  const char  *str,
```suggestion
  const char  *restrict s,
```
Be compatible with fputs(3). I don't see other uses of `restrict` in EDK2, but I don't know why we wouldn't use it. Would need a maintainer to comment.

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/Include/CrtLibSupport.h
> +  char  *strSource
```suggestion
  char  *s
```
strdup(3) name choice.

A shame, but it is what it is.

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c
> +  FILE  *fp
```suggestion
  FILE  *stream
```
feof(3) name.

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c
> +  FILE  *fp
```suggestion
  FILE  *stream
```
ftell(3) name.

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c
> +  int   n,
```suggestion
  char  *s,
  int   size,
```
fgets(3) names.

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c
> +  char  *strSource
```suggestion
  char  *s
```
strdup(3) name.

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c
> +  UINTN  len;
```suggestion
  UINTN  Length;
```
Follow EDK2 style guide.

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/Include/CrtLibSupport.h
> +  FILE  *fp
```suggestion
  FILE  *stream
```
ferror(3) name.

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/Include/CrtLibSupport.h
> +  FILE  *fp
```suggestion
  FILE  *stream
```
feof(3) name.

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/Include/CrtLibSupport.h
> +  int   n,
```suggestion
  char  *s,
  int   size,
```
fgets(3) names.

2024-11-30 23:07 UTC, deeglaze commented on CryptoPkg/Library/Include/CrtLibSupport.h
> +  FILE  *fp
```suggestion
  FILE  *stream
```
ftell(3) name.

2024-12-12 09:31 UTC, closed without merging